Resources:
  PanicSubmitsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: submitDate
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName : id
          KeyType : HASH
        - AttributeName : submitDate
          KeyType : RANGE
      TableClass: STANDARD
      TableName: PanicSubmits


Outputs:
  PanicSubmitsTableName:
    Description: The table name of panic submits in dynamodb
    Value: !Ref PanicSubmitsTable
  PanicSubmitsTableArn:
    Description: The table name of panic submits in dynamodb
    Value: !GetAtt PanicSubmitsTable.Arn