Resources:
  PanicRequestsTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
        - AttributeName: dateCreated
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName : id
          KeyType : HASH
        - AttributeName : dateCreated
          KeyType : RANGE
      TableName: PanicRequests

Outputs:
  PanicRequestsTableName:
    Export:
      Name: PanicRequestsTable-Name
    Description: The table name of panic requests in dynamodb
    Value: !Ref PanicRequestsTable
  PanicRequestsTableArn:
    Export:
      Name: PanicRequestsTable-Arn
    Description: The table name of panic requests in dynamodb
    Value: !GetAtt PanicRequestsTable.Arn